# PRUNE IS USING TO DELETE ALL OF STUFF ON DOCKER THAT ARE NO LONGER USED

# DELETE THE IMAGE ARE NO USED
docker image prune

# DELETE THE CONTAINER ARE NO USED
docker container prune

# DELETE THE VOLUME ARE NO USED
docker volume prune

# DELETE THE NETWORK ARE NO USED
docker network prune

# TO DELETE ALL OF STUFF(IMAGE, CONTAINER, AND NETWORK) EXCLUDE "VOLUME"
docker system prune

