firsrtname: Hasan
lastname: Almunawar
hobbies:
  - Coding
  - Scrolling

address:
  street: Jl. 2
  city: Sarolangun
  country: Indonesian

wallet:
  - type: cash
    ammount: 10000
  - type: debit
    ammount: 200000
