
services:
  app:
    container_name: app
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app_golang:1.0.0"
    environment:
      - "APP-PORT=8080"
    ports:
      - "8080:8080"