

services:

  mongodb11:
    image: mongo:latest
    container_name: mongodb11
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hasan
      MONGO_INITDB_ROOT_PASSWORD: hasan
      MONGO_INITDB_DATABASE: admin

    volumes:
      - "mongo-data1:/data/db"

  mongodb22:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hasan
      MONGO_INITDB_ROOT_PASSWORD: hasan
      MONGO_INITDB_DATABASE: admin

    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2
