
FROM alpine:3

LABEL author="Hasan Almunawar"
LABEL company="Hasan Patners" website="https://www.hasanalmunawr.com"

RUN mkdir hello
RUN echo "Hello world" > "hello/world.txt"

CMD cat "hello/world.txt"